Repository aave-starknet-project/aave-starknet-core, pull requests merged in 2022-09, with the labels that each got.

#116 Add pool configurator contract
  README.md
  contracts/interfaces/i_pool.cairo
  contracts/interfaces/i_pool_configurator.cairo
  contracts/protocol/libraries/helpers/bool_cmp.cairo
  contracts/protocol/libraries/logic/configurator_logic.cairo
  contracts/protocol/libraries/logic/validation_logic.cairo
  contracts/protocol/pool/pool_configurator.cairo
  contracts/protocol/pool/pool_configurator_library.cairo
  contracts/protocol/tokenization/a_token.cairo
  contracts/protocol/tokenization/a_token_library.cairo
  contracts/protocol/tokenization/base/incentivized_erc20_library.cairo
  contracts/protocol/tokenization/stable_debt_token_library.cairo
  contracts/protocol/tokenization/variable_debt_token_library.cairo
  protostar.toml
  tests/mocks/mock_pool_v1.cairo
  tests/mocks/mock_pool_v2.cairo
  tests/mocks/mock_token.cairo
  tests/test_suites/with_deployment/test_runs.cairo
  tests/unit_tests/protocol/libraries/aave_upgradeability/test_initializable_immutable_admin_upgradeability_proxy.cairo
  tests/unit_tests/protocol/pool/test_pool_configurator.cairo
Labels: feature

#140 cache cairo-lang
  .github/workflows/cairo-format.yml
  requirements.txt
Labels: enhancement

#136 SafeFeltMath library
  contracts/protocol/libraries/helpers/bool_cmp.cairo
  contracts/protocol/libraries/math/felt_math.cairo
  contracts/protocol/libraries/math/helpers.cairo
  contracts/protocol/libraries/math/safe_felt_math.cairo
  tests/unit_tests/protocol/libraries/math/test_helpers.cairo
  tests/unit_tests/protocol/libraries/math/test_safe_felt_math.cairo
Labels: feature

#131 Securing math operations from overflows
  contracts/protocol/libraries/math/math_utils.cairo
  contracts/protocol/libraries/math/percentage_math.cairo
  contracts/protocol/libraries/math/wad_ray_math.cairo
  contracts/protocol/tokenization/base/scaled_balance_token_library.cairo
  contracts/protocol/tokenization/stable_debt_token_library.cairo
  tests/unit_tests/protocol/libraries/math/test_percentage_math.cairo
Labels: fix
